---

- hosts: local-server
  become: yes
  become_user: root
  vars:
    apps:
      - python
      - emacs
      - git
      - zsh
  tasks:
    - command: cp -r ~/ansible/.emacs.d ~/
    - command: cp ~/ansible/.zshrc ~/
    - name: be sure app is installed
      apt: name={{ item }} state=installed
      with_items: "{{ apps }}"
    - git: repo=https://github.com/longld/peda.git dest=~/peda version=master 
    - name: "install peda"
      command: echo "source ~/peda/peda.py" >> ~/.gdbinit
    - git: repo=https://github.com/zsh-users/zsh-autosuggestions dest=~/.zsh/zsh-autosuggestions